import '../src/styles/globals.css';
import { Inter } from 'next/font/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={`${inter.variable} font-sans px-4 lg:px-40`}>
        <div className='navbar flex justify-between items-center py-3 backdrop-blur-md sticky top-0'>
          <div className='nav-list'>
            <ul className='flex justify-start gap-4 text-sm text-slate-600'>
              <li>
                <a href="#intro">Home</a>
              </li>
              <li>
                <a href="#about">About</a>
              </li>
              <li>
               <a href="#projects">Projects</a>
              </li>
            </ul>
          </div>
          <div>
            <img src="/memoji1.png" alt="" className='w-10' />
          </div>
        </div>

        {children}

      </body>
    </html>
  )
}
