import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { FaArrowAltCircleDown, FaArrowDown, FaBeer, FaCss3, FaDribbble, FaFigma, FaGithub, FaInstagram, FaLaravel, FaLinkedin, FaReact, FaRegMoon } from "react-icons/fa";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='p-8 min-h-screen'>
        <div className='flex justify-between z-10 bg-white -mt-4 py-4'>
          <h3 className='text-sm text-cyan-500 font-medium'>
            Hello!
          </h3>
          <div className='text-cyan-500'>
            <span>👋</span>
          </div>
        </div>


        <section className='-mt-16 mx-auto pt-20 text-center min-h-screen'>
          <div className=''>
            <img src="/memoji.png" alt="" sizes='cover' className='w-40 mt-20 mb-6 mx-auto bg-cover' />
          </div>

          <h3 className='text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-purple-500 mt-2'>
            Riyan Sandhiprasta
          </h3>

          <ul className='flex justify-around gap-1 mx-auto w-44 mt-3 text-cyan-500 font-medium'>
            <li>
              Front-End
            </li>
            <li>|</li>
            <li>
              Designer
            </li>
          </ul>

          <div className='flex justify-center gap-6 text-xl text-purple-500 mt-8'>
            <FaInstagram/>
            <FaLinkedin/>
            <FaGithub/>
            <FaDribbble/>
          </div>

          <a href='#about' className='text-[2rem] flex justify-center mt-28 text-cyan-300 animate-bounce'>
            <FaArrowDown className=''/>
          </a>
        </section>

        {/* BATAS SECTION INTRO - ABOUT*/}

        <section id='about' className='mt-2 mb-40 max-h-screen pt-20 place-items-center'>
          <h1 className='text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-purple-500 mb-8'>
            About <br/> Me
          </h1>
          <img src="/profile.png" alt="" className='w-40 rounded-full mt-6 mb-8' />
          <p className='text-slate-600 mb-8'>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero exercitationem incidunt voluptate, officia illum vel, nihil soluta quae aliquam, hic obcaecati adipisci! Omnis officia libero obcaecati, iure sed consequuntur reprehenderit.
          </p>
          <a href="http://" className='text-cyan-500 border-1 border-cyan-400 py-1 px-2 rounded-md shadow-lg shadow-cyan-100 text-sm hover:cursor-pointer hover:shadow-md'>
            Curicullum Vitae
          </a>
        </section>

        {/* BATAS SECTION ABOUT - START PROJECT */}

        <section className='mb-24'>
          <div>
            <h1 className='text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-purple-500 mb-8'>
              Latest Designs Work
            </h1>

            <div className='grid grid-cols-1 gap-8'>
              <div className='border border-slate-400 p-3 rounded-lg'>
                <img src="/SewaMobil.png" alt="" className='rounded-lg'/>
                <h5 className='text-cyan-500 font-semibold text-2xl mt-4'>
                  SewaMobil.id - Study Case
                </h5>
                <p className='text-slate-500 mt-2'>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, reprehenderit!
                </p>
              </div>
              <div className='border border-slate-400 p-3 rounded-lg'>
                <img src="/BaliProv.png" alt="" className='rounded-lg'/>
                <h5 className='text-cyan-500 font-semibold text-2xl mt-4'>
                  BaliProv.id - Web Redesign
                </h5>
                <p className='text-slate-500 mt-2'>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, reprehenderit!
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* BATAS SECTION PROJECT - START TECH */}

        <section>
          <h1 className='text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-500 to-purple-500 mb-8'>
            Technologies <br/> That I Use
          </h1>

          <div className='flex justify-start text-purple-400 text-6xl gap-4 mt-4 min-h-screen'>
            <FaFigma/>
            <FaReact/>
            <FaLaravel/>
          </div>
        </section>
      </main>
    </>
  )
}
